### ISSUE TITLE
How we would get updates from upstream?

### ISSUE THREAD

**Issue by Yeti-or** [bem/create-bem-react-app#20]
just merge `facebookincubator/create-react-app:master` ?

@awinogradov other ideas?

**Comment by awinogradov** [comment]
We don't need updates – we are independent! ;)

Best regards

Anton Winogradov
winogradovaa@gmail.com

**Comment by Yeti-or** [comment]
@awinogradov  It's a joke?

**Comment by Vittly** [comment]
We need updates. For example jest `toMatchObject` don't support `stringMatching` in current 18 version. Current `create-react-app` has jest 20!

**Comment by awinogradov** [comment]
Anybody can make PR with updates in package.json or something else
